# Site settings
title: Kisallioppiminen.fi
baseurl: ""
url: "https://ohtukisalli.github.io/dev-frontend"
backendbaseurl: "https://pure-inlet-98383.herokuapp.com/"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

encoding: UTF-8
sass:
  style: :compressed

navigation:
  "Materiaalit": "/"
  "Blogi": "http://blogs.helsinki.fi/kisallioppiminenlukiossa"
  "Tietoa": "/tietoa.html"

resources:
  css:
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/css/main.css"
  js:
    - "/js/common.js"
    - "//code.jquery.com/jquery-2.2.4.min.js"
    - "/js/session.js"
    - "/js/view.js"
    - "/js/exercises.js"
    - "/js/backend.js"
    - "/js/mooc.js"
    - "/js/button/button.js"
    - "/js/init.js"
    - "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"


exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
