# Site settings
title: Kisallioppiminen.fi
baseurl: ""
### site.url no longer needed? ###
#url: "https://beta-kisallioppiminen.github.io"
### Change this in production ###
#backendbaseurl: "http://kurssihallinta.kisallioppiminen.fi/"
backendbaseurl: "https://pure-inlet-98383.herokuapp.com/"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

encoding: UTF-8
sass:
  style: :compressed

navigation:
  "Materiaalit": "/"
  "Blogi": "http://blogs.helsinki.fi/kisallioppiminenlukiossa"
  "Tietoa": "/tietoa.html"
  # Login button added with js

resources:
  css:
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/css/main.css"
  js:
    # Download libraries
    - "//code.jquery.com/jquery-2.2.4.min.js"

    # Download own scripts
    - "/js/common.js"
    - "/js/session.js"
    - "/js/view.js"
    - "/js/exercises.js"
    - "/js/backend.js"
    - "/js/mooc.js"
    - "/js/button/button.js"
    - "/js/init.js"


exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
